config/routes.rb
PiaDiary::Application.routes.draw do
  resources :composers


  resources :songs


  resources :practices

  get '/' => "top#index"
  
end

app/models/composer.rb
class Composer < ActiveRecord::Base
  attr_accessible :country, :name
end

app/models/practice.rb
class Practice < ActiveRecord::Base
  attr_accessible :practice_begin, :practice_end, :song_id
end

app/models/song.rb
class Song < ActiveRecord::Base
  attr_accessible :composer_id, :key, :memo_id, :name, :opus
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/composers_controller.rb
class ComposersController < ApplicationController
  # GET /composers
  # GET /composers.json
  def index
    @composers = Composer.all
  end

  # GET /composers/1
  # GET /composers/1.json
  def show
    @composer = Composer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @composer }
    end
  end

  # GET /composers/new
  # GET /composers/new.json
  def new
    @composer = Composer.new
  end

  # GET /composers/1/edit
  def edit
    @composer = Composer.find(params[:id])
  end

  # POST /composers
  # POST /composers.json
  def create
    @composer = Composer.new(params[:composer])

    respond_to do |format|
      if @composer.save
        format.html { redirect_to @composer, notice: 'Composer was successfully created.' }
        format.json { render json: @composer, status: :created, location: @composer }
      else
        format.html { render action: "new" }
        format.json { render json: @composer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /composers/1
  # PUT /composers/1.json
  def update
    @composer = Composer.find(params[:id])

    respond_to do |format|
      if @composer.update_attributes(params[:composer])
        format.html { redirect_to @composer, notice: 'Composer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @composer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /composers/1
  # DELETE /composers/1.json
  def destroy
    @composer = Composer.find(params[:id])
    @composer.destroy

    respond_to do |format|
      format.html { redirect_to composers_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/practices_controller.rb
class PracticesController < ApplicationController
  # GET /practices
  # GET /practices.json
  def index
    @practices = {}
    days = Practice.pluck(:practice_begin).map{|t| Date.strptime(t.to_s, "%Y-%m-%d") }.uniq.sort{|a,b| (-1) * (a <=> b)}
    days.each do |day|
      @practices[day] = Practice.where('practice_begin > ? AND practice_begin < ?', day, day.tomorrow)
    end
  end

  # GET /practices/1
  # GET /practices/1.json
  def show
    @practice = Practice.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @practice }
    end
  end

  # GET /practices/new
  # GET /practices/new.json
  def new
    t = Time.now
    default = {
      :practice_begin => t,
      :practice_end => t + 1.hour
    }
    @songs = Song.all
    @practice = Practice.new(default)
    #@practice.song_memo.create
  end

  # GET /practices/1/edit
  def edit
    @practice = Practice.find(params[:id])
  end

  # POST /practices
  # POST /practices.json
  def create
    @practice = Practice.new(practice_params)
    p @practice
    #@song_memo = SongMemo.new(song_memo_params)
    
    respond_to do |format|
      if @practice.save!
        format.html { redirect_to '/practices', notice: 'Practice was successfully created.' }
        format.json { render action: 'show', status: :created, location: @practice }
      else
        @songs = Song.all
        format.html { render action: 'new' }
        format.json { render json: @practice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /practices/1
  # PUT /practices/1.json
  def update
    @practice = Practice.find(params[:id])

    respond_to do |format|
      if @practice.update_attributes(params[:practice])
        format.html { redirect_to @practice, notice: 'Practice was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @practice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /practices/1
  # DELETE /practices/1.json
  def destroy
    @practice = Practice.find(params[:id])
    @practice.destroy

    respond_to do |format|
      format.html { redirect_to practices_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/songs_controller.rb
# coding: utf-8
class SongsController < ApplicationController
  KEYS = {
    'ハ長調' => 'C',
    'ト長調' => 'G',
    'ニ長調' => 'D',
    'イ長調' => 'A',
    'ホ長調' => 'E',
    'ロ長調' => 'B',
    '嬰ヘ長調' => 'Fs',
    '嬰ハ長調' => 'Cs',
    '変イ長調' => 'Af',
    '変ホ長調' => 'Ef',
    '変ロ長調' => 'Bf',
    'ヘ長調' => 'F',
    'イ短調' => 'Am',
    'ホ短調' => 'Em',
    'ロ短調' => 'Bm',
    '嬰ヘ短調' => 'Fsm',
    '嬰ハ短調' => 'Csm',
    '嬰ト短調' => 'Gsm',
    '嬰ニ短調' => 'Dsm',
    '嬰イ短調' => 'Asm',
    'ヘ短調' => 'Fm',
    'ハ短調' => 'Cm',
    'ト短調' => 'Gm',
    'ニ短調' => 'Dm'
  }

  # GET /songs
  # GET /songs.json
  def index
    @songs = { }
    
    cmp_names = Composer.pluck(:name)
    cmp_ids = Composer.pluck(:id)
    cmps = cmp_names.zip(cmp_ids)
    
    cmps.each do |cmp|
      @songs[cmp[0]] = Song.where('composer_id = ?', cmp[1]) 
    end
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
    @song = Song.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @song }
    end
  end

  # GET /songs/new
  # GET /songs/new.json
  def new
    @song = Song.new
    @composers = Composer.all
  end

  # GET /songs/1/edit
  def edit
    @song = Song.find(params[:id])
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(params[:song])

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render json: @song, status: :created, location: @song }
      else
        format.html { render action: "new" }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /songs/1
  # PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.iphone { redirect_to @song, notice: 'Song was successfully updated.' }
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.iphone { redirect_to songs_url }
      format.html { redirect_to songs_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/composers_helper.rb
module ComposersHelper
end

app/helpers/practices_helper.rb
module PracticesHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/composers/_form.html.erb
<%= form_for(@composer) do |f| %>
  <% if @composer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@composer.errors.count, "error") %> prohibited this composer from being saved:</h2>

      <ul>
      <% @composer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/composers/edit.html.erb
<h1>Editing composer</h1>

<%= render 'form' %>

<%= link_to 'Show', @composer %> |
<%= link_to 'Back', composers_path %>

app/views/composers/index.html.erb
<h1>Listing composers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Country</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @composers.each do |composer| %>
      <tr>
        <td><%= composer.name %></td>
        <td><%= composer.country %></td>
        <td><%= link_to 'Show', composer %></td>
        <td><%= link_to 'Edit', edit_composer_path(composer) %></td>
        <td><%= link_to 'Destroy', composer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Composer', new_composer_path %>

app/views/composers/new.html.erb
<h1>New composer</h1>

<%= render 'form' %>

<%= link_to 'Back', composers_path %>

app/views/composers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @composer.name %>
</p>

<p>
  <strong>Country:</strong>
  <%= @composer.country %>
</p>

<%= link_to 'Edit', edit_composer_path(@composer) %> |
<%= link_to 'Back', composers_path %>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="ja">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>練習登録</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div data-role="page">

  <%= yield %>

  </div>
</body>
</html>

app/views/layouts/iphone.iphone.erb
<!doctype html>
<html lang="ja">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>練習登録</title>
  <%= stylesheet_link_tag    "mobile_application" %>
  <%= javascript_include_tag "mobile_application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div data-role="page">

  <%= yield %>

  </div>
</body>
</html>

app/views/practices/_form.html.erb
<%= form_for(@practice) do |f| %>
  <% if @practice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@practice.errors.count, "error") %> prohibited this practice from being saved:</h2>

      <ul>
      <% @practice.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
    <% end %>

    <div class="field">
      <%= f.label :practice_begin  %><br />
      <%= f.datetime_select :practice_begin, :use_month_numbers => true, :minute_step => 10 %>
    </div>
    <div class="field">
      <%= f.label :practice_end  %><br />
      <%= f.datetime_select :practice_end, :use_month_numbers => true, :minute_step => 10 %>
    </div>
    <div class="field">
      <%= f.label :song  %><br />
      <%= f.collection_select(:song_id, @songs, :id, :name, :prompt => "選択してください") %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
    <% end %>

app/views/practices/edit.html.erb
<h1>Editing practice</h1>

<%= render 'form' %>

<%= link_to 'Show', @practice %> |
<%= link_to 'Back', practices_path %>

app/views/practices/index.html.erb
<div data-role="header">
  <%= link_to 'TOP', '/', "data-icon" => "home" %>
  <h1>練習一覧</h1>
</div>

<p id="notice"><%= notice %></p>

<ul data-role="listview">
  <% @practices.each do |day, practices| %>
  <li data-role="list-divider"><%= day %><span class="ui-li-count"><%= practices.size %>曲</span></li>
    <% practices.each do |practice| %>
    <li>
      <%= link_to practice.song.name, practice %>
      <p class="ui-li-aside"><strong><%= practice.practice_begin.strftime("%H:%M") %>-<%= practice.practice_end.strftime("%H:%M") %></strong></p>
    </li>
    <% end %>
  <% end %>
</ul>
<br>

app/views/practices/index.iphone.erb
<div data-role="header">
  <%= link_to 'TOP', '/', "data-icon" => "home" %>
  <h1>練習一覧</h1>
</div>

<p id="notice"><%= notice %></p>

<ul data-role="listview">
  <% @practices.each do |day, practices| %>
  <li data-role="list-divider"><%= day %><span class="ui-li-count"><%= practices.size %>曲</span></li>
    <% practices.each do |practice| %>
    <li>
      <%= link_to practice.song.name, practice %>
      <p class="ui-li-aside"><strong><%= practice.practice_begin.strftime("%H:%M") %>-<%= practice.practice_end.strftime("%H:%M") %></strong></p>
    </li>
    <% end %>
  <% end %>
</ul>
<br>

app/views/practices/new.html.erb
<div data-role="header">
  <%= link_to 'TOP', '/', "data-icon" => "home" %>
  <h1>練習記録</h1>
</div>

<%= form_for(@practice) do |f| %>
  <% if @practice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@practice.errors.count, "error") %> prohibited this practice from being saved:</h2>

      <ul>
      <% @practice.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
    <% end %>

    <div class="field">
      <div data-role="fieldcontain">
      日付
      <fieldset data-role="controlgroup" data-type="horizontal">
        <%= f.date_select :practice_begin %>
      <fieldset>
      </div>
    </div>

    <div class="field">
      <div data-role="fieldcontain">
      <%= f.label :practice_begin  %>
      <fieldset data-role="controlgroup" data-type="horizontal">
      <%= f.time_select :practice_begin, :use_month_numbers => true, :minute_step => 10, :time_separator => '' %>
      <fieldset>
      </div>
    </div>

    <div class="field">
      <div data-role="fieldcontain">
	<%= f.label :practice_end  %>
	<fieldset data-role="controlgroup" data-type="horizontal">
	  <%= f.time_select :practice_end, :use_month_numbers => true, :minute_step => 10, :time_separator => '' %>
      </fieldset>
      </div>
    </div>
    <div class="field">
      <div data-role="fieldcontain">
	<%= f.label :song  %>
	<%= f.collection_select(:song_id, @songs, :id, :name, :prompt => "選択してください") %>
      </div>
    </div>

    <%= f.fields_for :song_memo do |memo| %>
    <div class="field">
     <div data-role="fieldcontain">
	<%= memo.label :memo %>
	<%= memo.text_area :memo %>
      </div>
    </div>
    <% end %>

    <div class="actions">
      <%= f.submit %>
    </div>
    <% end %>
<br />

app/views/practices/new.iphone.erb
<div data-role="header">
  <%= link_to 'TOP', '/', "data-icon" => "home" %>
  <h1>練習記録</h1>
</div>

<%= form_for(@practice) do |f| %>
  <% if @practice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@practice.errors.count, "error") %> prohibited this practice from being saved:</h2>

      <ul>
      <% @practice.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
    <% end %>

    <div class="field">
      <div data-role="fieldcontain">
      日付
      <fieldset data-role="controlgroup" data-type="horizontal">
        <%= f.date_select :practice_begin %>
      <fieldset>
      </div>
    </div>

    <div class="field">
      <div data-role="fieldcontain">
      <%= f.label :practice_begin  %>
      <fieldset data-role="controlgroup" data-type="horizontal">
      <%= f.time_select :practice_begin, :use_month_numbers => true, :minute_step => 10, :time_separator => '' %>
      <fieldset>
      </div>
    </div>

    <div class="field">
      <div data-role="fieldcontain">
	<%= f.label :practice_end  %>
	<fieldset data-role="controlgroup" data-type="horizontal">
	  <%= f.time_select :practice_end, :use_month_numbers => true, :minute_step => 10, :time_separator => '' %>
      </fieldset>
      </div>
    </div>
    <div class="field">
      <div data-role="fieldcontain">
	<%= f.label :song  %>
	<%= f.collection_select(:song_id, @songs, :id, :name, :prompt => "選択してください") %>
      </div>
    </div>

    <%= f.fields_for :song_memo do |memo| %>
    <div class="field">
     <div data-role="fieldcontain">
	<%= memo.label :memo %>
	<%= memo.text_area :memo %>
      </div>
    </div>
    <% end %>

    <div class="actions">
      <%= f.submit %>
    </div>
    <% end %>
<br />

app/views/practices/show.html.erb
<div data-role="header">
  <h1><%= @practice.practice_begin.strftime("%Y-%m-%d") %>: <%= @practice.song.name %></h1>
</div>

曲名：<%= @practice.song.name %><br />
練習時間：<%= @practice.practice_begin.strftime("%H:%M") %>〜<%= @practice.practice_end.strftime("%H:%M") %><br />
メモ：<%= @practice.song.memo %><br />
<%= button_to '削除', "/practices/#{@practice.id}", :method => :delete, 'data-role' => 'button', 'data-theme' => 'a' %>
<%= link_to '一覧に戻る', practices_path %>

app/views/practices/show.iphone.erb
<div data-role="header">
  <h1><%= @practice.practice_begin.strftime("%Y-%m-%d") %>: <%= @practice.song.name %></h1>
</div>

曲名：<%= @practice.song.name %><br />
練習時間：<%= @practice.practice_begin.strftime("%H:%M") %>〜<%= @practice.practice_end.strftime("%H:%M") %><br />
メモ：<%= @practice.song.memo %><br />
<%= button_to '削除', "/practices/#{@practice.id}", :method => :delete, 'data-role' => 'button', 'data-theme' => 'a' %>
<%= link_to '一覧に戻る', practices_path %>

app/views/songs/_form.html.erb
<%= form_for(@song) do |f| %>
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% @song.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/songs/edit.html.erb
<h1>Editing song</h1>

<%= render 'form' %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index.html.erb
<div data-role="header">
<h1>曲一覧</h1>
</div>
<ul data-role="listview">
  <% @songs.each do |cmp, songs| %>
  <li data-role="list-divider"><%= cmp %><span class="ui-li-count"><%= songs.size %></span></li>
    <% songs.each do |song| %>
    <li>
      <%= link_to song.name, song %>
      <p class="ui-li-aside"><strong>Op.<%= song.opus %></strong></p>
    </li>
    <% end %>
  <% end %>
</ul>
<br>

app/views/songs/index.iphone.erb
<div data-role="header">
<h1>曲一覧</h1>
</div>
<ul data-role="listview">
  <% @songs.each do |cmp, songs| %>
  <li data-role="list-divider"><%= cmp %><span class="ui-li-count"><%= songs.size %></span></li>
    <% songs.each do |song| %>
    <li>
      <%= link_to song.name, song %>
      <p class="ui-li-aside"><strong>Op.<%= song.opus %></strong></p>
    </li>
    <% end %>
  <% end %>
</ul>
<br>

<%= link_to '戻る', '/' %>

app/views/songs/new.html.erb
<div data-role="header" data-position="inline">
  <%= link_to 'TOP', '/', "data-icon" => "home" %>
  <h1>曲登録</h1>
  <%= link_to '作曲者追加', '#', "data-icon" => "plus" %>
</div>

<%= form_for(@song) do |f| %>
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% @song.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field", data-role="fieldcontain">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field", data-role="fieldcontain">
    <%= f.label :composer %>
    <%= f.collection_select(:id, @composers, :id, :name, :prompt => "選択してください") %>
  </div>
  <div class="field", data-role="fieldcontain" >
    <%= f.label :opus %>
    <%= f.text_field :opus %>
  </div>
  <div class="field", data-role="fieldcontain">
    <%= f.label :key %>
    <%= f.select :key, SongsController::KEYS %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/songs/new.iphone.erb
<div data-role="header" data-position="inline">
  <%= link_to 'TOP', '/', "data-icon" => "home" %>
  <h1>曲登録</h1>
  <%= link_to '作曲者追加', '#', "data-icon" => "plus" %>
</div>

<%= form_for(@song) do |f| %>
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% @song.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field", data-role="fieldcontain">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field", data-role="fieldcontain">
    <%= f.label :composer %>
    <%= f.collection_select(:id, @composers, :id, :name, :prompt => "選択してください") %>
  </div>
  <div class="field", data-role="fieldcontain" >
    <%= f.label :opus %>
    <%= f.text_field :opus %>
  </div>
  <div class="field", data-role="fieldcontain">
    <%= f.label :key %>
    <%= f.select :key, SongsController::KEYS %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_song_path(@song) %> |
<%= link_to 'Back', songs_path %>

app/views/songs/show.iphone.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_song_path(@song) %> |
<%= link_to 'Back', songs_path %>

app/views/top/index.html.erb
<div data-role="header">
  <h1>ピアノ練習記録</h1>
</div>

<div data-role="content">
<div class="content-primary main-content">
<ul data-role='listview' data-theme='g'>
  <li><%= link_to '記録', new_practice_path %></li>
  <li><%= link_to '閲覧', practices_path %></li>
  <li><%= link_to '曲登録', new_song_path %></li>
  <li><%= link_to '曲閲覧', songs_path %></li>
</ul>
</div>
</div>

app/views/top/index.iphone.erb
<div data-role="header">
  <h1>ピアノ練習記録</h1>
</div>

<div data-role="content">
<div class="content-primary main-content">
<ul data-role='listview' data-theme='g'>
  <li><%= link_to '記録', new_practice_path %></li>
  <li><%= link_to '閲覧', practices_path %></li>
  <li><%= link_to '曲登録', new_song_path %></li>
  <li><%= link_to '曲閲覧', songs_path %></li>
</ul>
</div>
</div>